# Generated by Django 5.1.7 on 2025-05-17 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TT', 'Tout-terrain'), ('FM', 'Familiale')], default='FM', max_length=2, verbose_name='Type de véhicule')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('prix_journalier', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix journalier (€)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='voitures/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('AT', 'En attente de paiement'), ('EC', 'En cours'), ('TR', 'Terminé'), ('AN', 'Annulé')], default='AT', max_length=2, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('paiement_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de paiement')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant total (€)')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='rental.voiture', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
